---
- name: install jenkins container
  hosts: all
  remote_user: vagrant  # Change remote user to your sudo user!
  become: true
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: run jenkins on port 8080
      shell: docker pull jenkins/jenkins 

    - name: xd
      shell: docker run -p 8080:8080 --name=jenkins-master -d jenkins/jenkins
